name = "private-photo"
compatibility_date = "2024-08-01"

# 安全相关环境变量
[vars]
# JWT配置 - 生产环境请务必修改为强密钥
JWT_SECRET = "请替换为至少32位的随机字符串"
JWT_EXPIRES_IN = "3600" # 令牌有效期(秒)

# 上传限制
ALLOWED_FILE_TYPES = "image/jpeg,image/png,image/gif,image/webp,video/mp4,video/webm,video/ogg"
MAX_FILE_SIZE_BYTES = "52428800" # 50MB
MAX_STORAGE_BYTES = "6442450944" # 6GB
UPLOAD_PREFIX = "uploads/"

# 速率限制
RATE_LIMIT_REQUESTS = "10" # 每分钟请求数限制
RATE_LIMIT_WINDOW_MS = "60000" # 限制窗口(毫秒)

# KV 命名空间绑定（用于速率限制）
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "RATE_LIMIT_KV_ID"

# KV 命名空间绑定（用于访客访问状态）
[[kv_namespaces]]
binding = "GUEST_ACCESS_KV"
id = "GUEST_ACCESS_KV_ID"